### ISSUE TITLE
Importing just the type definitions from a package causes it to be bundled

### ISSUE THREAD

**Issue by boris-petrov** [ef4/ember-auto-import#237] opened 2019-08-01 09:51 UTC
Having the following code:

```typescript
import { Calendar, PluginDef } from '@fullcalendar/core';

export default async function(): Promise<[typeof Calendar, PluginDef]> {
  const result = await Promise.all([
    import('@fullcalendar/core'),
    import('@fullcalendar/daygrid'),
  ]);
  return [result[0].Calendar, result[1].default];
}
```

Causes `ember-auto-import` to put `@fullcalendar/core` in `vendor.js` and only `@fullcalendar/daygrid` as a chunk. If I remove the import of the type-definitions and change the code to something like:

```typescript
export default async function(): Promise<any> {
  const result = await Promise.all([
    import('@fullcalendar/core'),
    import('@fullcalendar/daygrid'),
  ]);
  return [result[0].Calendar, result[1].default];
}
```

Then both packages are put in chunks and neither in `vendor.js`.

I believe this is a bug.

**Comment by ef4** [comment] 2019-08-05 16:36
Yeah, this is a bug. The latest discussion around this is in https://github.com/ef4/ember-auto-import/issues/169.

I'm going to close this as a duplicate of the solution suggested there.

**Closed by ef4** 2019-08-05 16:36 UTC
