### ISSUE TITLE
ember-auto-import breaks after ember-upgrade

### ISSUE THREAD

**Issue by Houndsto0th** [ef4/ember-auto-import#203] opened 2019-04-02 17:21 UTC
I'm in the process of upgrading an ember app and it's addons from ember source 3.2.0 to 3.8.0. After running the ember-cli-upgrade and appropriate codemods I find myself getting the following error:
```
Build Error (Bundler)

webpack returned errors to ember-auto-import


Stack Trace and Error Report: /var/folders/8z/1v8tj2s57z555n286kzrvp1w0000gp/T/error.dump.983aefeb296de1aebb48802f422e650a.log
```

and when I view that log I see 4 of the following error:

```
broccoliBuilderErrorStack: Error: webpack returned errors to ember-auto-import
    at webpack.run (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-auto-import/js/webpack.js:157:32)
    at finalCallback (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:214:39)
    at hooks.done.callAsync.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:263:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bkinnear/EdMeas/trash-panda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/bkinnear/EdMeas/trash-panda/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:261:22)
    at Compiler.emitRecords (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:375:39)
    at emitAssets.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:255:10)
    at hooks.afterEmit.callAsync.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:361:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bkinnear/EdMeas/trash-panda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
  - code: [undefined]
  - codeFrame: webpack returned errors to ember-auto-import
  - errorMessage: webpack returned errors to ember-auto-import
        at Bundler
```

I'm happy to attach my list of dev dependencies or run through any other troubleshooting steps necessary.

**Comment by ef4** [comment] 2019-04-02 18:56
Please share the actual errors. They are hiding inside that error.dump file.

**Comment by Houndsto0th** [comment] 2019-04-02 19:05
```
=================================================================================

ENV Summary:

  TIME: Tue Apr 02 2019 11:18:05 GMT-0600 (MDT)
  TITLE: ember
  ARGV:
  - /Users/bkinnear/.nodenv/versions/8.11.3/bin/node
  - /Users/bkinnear/.nodenv/versions/8.11.3/bin/ember
  - s
  EXEC_PATH: /Users/bkinnear/.nodenv/versions/8.11.3/bin/node
  TMPDIR: /var/folders/8z/1v8tj2s57z555n286kzrvp1w0000gp/T
  SHELL: /bin/zsh
  PATH:
  - /Users/bkinnear/.nodenv/versions/8.11.3/bin
  - /usr/local/Cellar/nodenv/1.1.2/libexec
  - /Users/bkinnear/.nodenv/shims
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  PLATFORM: darwin x64
  FREEMEM: 298418176
  TOTALMEM: 17179869184
  UPTIME: 4245686
  LOADAVG: 3.498046875,3.33154296875,3.1796875
  CPUS:
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.32.0
  - node: 8.11.3
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: webpack returned errors to ember-auto-import
    at webpack.run (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-auto-import/js/webpack.js:157:32)
    at finalCallback (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:214:39)
    at hooks.done.callAsync.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:263:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bkinnear/EdMeas/trash-panda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/bkinnear/EdMeas/trash-panda/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:261:22)
    at Compiler.emitRecords (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:375:39)
    at emitAssets.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:255:10)
    at hooks.afterEmit.callAsync.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:361:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bkinnear/EdMeas/trash-panda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
  - code: [undefined]
  - codeFrame: webpack returned errors to ember-auto-import
  - errorMessage: webpack returned errors to ember-auto-import
        at Bundler
-~- created here: -~-
    at new Plugin (/Users/bkinnear/EdMeas/trash-panda/node_modules/broccoli-plugin/index.js:7:31)
    at new Bundler (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-auto-import/js/bundler.js:24:9)
    at AutoImport.makeBundler (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-auto-import/js/auto-import.js:55:16)
    at AutoImport.addTo (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-auto-import/js/auto-import.js:64:38)
    at EmberApp.host.addonPostprocessTree (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-auto-import/js/auto-import.js:93:29)
    at EmberApp.toTree (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-cli/lib/broccoli/ember-app.js:1772:17)
    at module.exports (/Users/bkinnear/EdMeas/trash-panda/ember-cli-build.js:40:14)
    at Builder.readBuildFile (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-cli/lib/models/builder.js:32:10)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: webpack returned errors to ember-auto-import
        at Bundler
-~- created here: -~-
    at new Plugin (/Users/bkinnear/EdMeas/trash-panda/node_modules/broccoli-plugin/index.js:7:31)
    at new Bundler (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-auto-import/js/bundler.js:24:9)
    at AutoImport.makeBundler (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-auto-import/js/auto-import.js:55:16)
    at AutoImport.addTo (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-auto-import/js/auto-import.js:64:38)
    at EmberApp.host.addonPostprocessTree (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-auto-import/js/auto-import.js:93:29)
    at EmberApp.toTree (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-cli/lib/broccoli/ember-app.js:1772:17)
    at module.exports (/Users/bkinnear/EdMeas/trash-panda/ember-cli-build.js:40:14)
    at Builder.readBuildFile (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-cli/lib/models/builder.js:32:10)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: Bundler
  - originalErrorMessage: webpack returned errors to ember-auto-import
  - stack: Error: webpack returned errors to ember-auto-import
    at webpack.run (/Users/bkinnear/EdMeas/trash-panda/node_modules/ember-auto-import/js/webpack.js:157:32)
    at finalCallback (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:214:39)
    at hooks.done.callAsync.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:263:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bkinnear/EdMeas/trash-panda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/bkinnear/EdMeas/trash-panda/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:261:22)
    at Compiler.emitRecords (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:375:39)
    at emitAssets.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:255:10)
    at hooks.afterEmit.callAsync.err (/Users/bkinnear/EdMeas/trash-panda/node_modules/webpack/lib/Compiler.js:361:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bkinnear/EdMeas/trash-panda/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)

=================================================================================
```

This is the entirety of the file from that "Stack Trace and Error Report"

**Comment by Houndsto0th** [comment] 2019-04-03 14:14
I just ran ```DEBUG=ember-auto-import* ember build``` and this is the end of that output:
```
  ember-auto-import:bundler extraWebpackConfig {} +0ms
Build Error (Bundler)

webpack returned errors to ember-auto-import


Stack Trace and Error Report: /var/folders/8z/1v8tj2s57z555n286kzrvp1w0000gp/T/error.dump.a9b693265c6f6455f6236b4e4f8a7821.log
```
Is there something about the extraWebpackConfig that could be causing the issue? is there a way for me to disable that?

**Comment by mdbiscan** [comment] 2019-06-14 19:24
I'm seeing this exact issue.

**Comment by Samsinite** [comment] 2019-09-25 16:25
We are getting a similar error here, has anyone found a solution?

**Comment by ef4** [comment] 2019-09-25 17:39
Can somebody share a reproduction? I don't have an instance of this bug to examine.

One thing you can try is to remove the `import` statements for each library you are auto-importing one-by-one to see if you can make the build succeed. That may narrow down what is breaking.

**Comment by Samsinite** [comment] 2019-09-25 17:55
:+1: we'll take a look. We had a few more things break than expected from 3.4-3.8, so we are just fixing a few deprecations in the current sprint. Might be 2 weeks until I'm able to provide an update.

**Comment by leondmello** [comment] 2020-03-22 21:46
Dunno if this is the same issue, but I see a deprecation warning when I import `sinon` in my tests
`import sinon, { SinonSpy } from 'sinon';`

Here's the stack
```js
DEPRECATION: String.prototype.singularize() is deprecated. Please explicitly: import { singularize } from 'ember-inflector'; [deprecation id: ember-inflector.globals]
    registerHandler/HANDLERS[type]@http://localhost:4200/assets/vendor.js:47123:17
    raiseOnDeprecation@http://localhost:4200/assets/vendor.js:47053:13
    registerHandler/HANDLERS[type]@http://localhost:4200/assets/vendor.js:47123:17
    invoke@http://localhost:4200/assets/vendor.js:47135:23
    deprecate@http://localhost:4200/assets/vendor.js:47091:28
    get@http://localhost:4200/assets/vendor.js:164973:15
    copyPrototypeMethods/<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:100:110
    copyPrototypeMethods@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:99:644
    [28]<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:100:1286
    s@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:399
    s/<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:450
    [24]<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:100:566
    s@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:399
    s/<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:450
    [19]<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:98:385
    s@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:399
    s/<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:450
    [11]<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:44:2420
    s@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:399
    s/<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:450
    [8]<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:34:1316
    s@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:399
    s/<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:450
    [12]<@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:77:3418
    s@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:399
    e@webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:574
    @webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:603
    @webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:62
    @webpack://__ember_auto_import__/./node_modules/nise/nise.js?:1:84
    ./node_modules/nise/nise.js@http://localhost:4200/assets/test-support.js:24517:1
    __webpack_require__@http://localhost:4200/assets/test-support.js:23823:30
    @webpack://__ember_auto_import__/./node_modules/sinon/lib/sinon/sandbox.js?:27:37
    ./node_modules/sinon/lib/sinon/sandbox.js@http://localhost:4200/assets/test-support.js:24709:1
    __webpack_require__@http://localhost:4200/assets/test-support.js:23823:30
    @webpack://__ember_auto_import__/./node_modules/sinon/lib/sinon/create-sandbox.js?:5:34
    ./node_modules/sinon/lib/sinon/create-sandbox.js@http://localhost:4200/assets/test-support.js:24589:1
    __webpack_require__@http://localhost:4200/assets/test-support.js:23823:30
    @webpack://__ember_auto_import__/./node_modules/sinon/lib/sinon.js?:5:40
    ./node_modules/sinon/lib/sinon.js@http://localhost:4200/assets/test-support.js:24529:1
    __webpack_require__@http://localhost:4200/assets/test-support.js:23823:30
    @webpack://__ember_auto_import__//private/var/folders/dy/398g6wkj31v7l2ghpjb6ggzm0000gr/T/broccoli-71574M0mqs5urwTjj/cache-674-bundler/staging/tests.js?:15:40
    Module.prototype.exports@http://localhost:4200/assets/vendor.js:118:32
    Module.prototype._reify@http://localhost:4200/assets/vendor.js:155:59
    Module.prototype.reify@http://localhost:4200/assets/vendor.js:142:27
    Module.prototype.exports@http://localhost:4200/assets/vendor.js:116:10
    requireModule@http://localhost:4200/assets/vendor.js:39:18
    require@http://localhost:4200/assets/test-support.js:19281:16
    loadModules@http://localhost:4200/assets/test-support.js:19274:14
    loadTests@http://localhost:4200/assets/test-support.js:21265:22
    start@http://localhost:4200/assets/test-support.js:20942:33
    @http://localhost:4200/assets/tests.js:574:25
    Module.prototype.exports@http://localhost:4200/assets/vendor.js:118:32
    requireModule@http://localhost:4200/assets/vendor.js:39:18
    @http://localhost:4200/assets/tests.js:790:8
```

**Comment by biannetta** [comment] 2021-06-15 21:29
I can confirm this is still an issue with v2.0.1. I specifically encountered this issue with the ember-cli-sass add on.

From package.json
ember-source: ~3.26.1
ember-auto-import: ^2.0.1
ember-cli-sass: ^10.0.1

Here's the console output

> ❯ ember serve
>Build Error (WebpackBundler)
>
>Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
> - configuration.target should be one of these:
>   "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | "electron-preload" | >function
>   -> Environment to build for
>   Details:
>    * configuration.target should be one of these:
>      "web" | "webworker" | "node" | "async-node" | "node-webkit" | "electron-main" | "electron-renderer" | "electron->preload"
>    * configuration.target should be an instance of function


Here's the error dump from the following command

[error.dump.047b3666bca3d02d24a7db0326314055.log](https://github.com/ef4/ember-auto-import/files/6658830/error.dump.047b3666bca3d02d24a7db0326314055.log)
 
Replication can be found on this branch here
https://github.com/biannetta/biannetta.com/tree/ember-auto-load-error

**Comment by ef4** [comment] 2021-06-15 21:32
@biannetta that is a different error. I'm pretty sure your case is due to not adding webpack 5 as documented in the [upgrade guide](https://github.com/ef4/ember-auto-import/blob/master/docs/upgrade-guide-2.0.md).

We have [a PR](https://github.com/ef4/ember-auto-import/pull/414) landing to give a more helpful error in that case.

**Comment by ef4** [comment] 2021-06-15 21:32
This issue is old and has no working reproduction and is misleading people so I'm closing it.

**Closed by ef4** 2021-06-15 21:32 UTC
