### ISSUE TITLE
installed in module-unification project, received errors

### ISSUE THREAD

**Issue by NullVoxPopuli** [ef4/ember-auto-import#6] opened 2018-06-04 19:23 UTC
![image](https://user-images.githubusercontent.com/199018/40932493-82b1b478-67fc-11e8-8992-6f7ee13a9a18.png)

looks like just `process` is undefined.
This is the commit I'm working from in my module unification app: https://github.com/NullVoxPopuli/emberclear/commit/f23affe66e4afc4ada7d3f545af71be0bd1621d0 (this is pre-ember-auto-import)

**Comment by ef4** [comment] 2018-06-05 05:19
I tried to get your app into this state but couldn't reproduce that exact error.

`process` is most definitely undefined, but it's not supposed to be defined. It's a node-ism that has no equivalent in the browser. Something is pulling in code that is not really portable. Please check out the area around the source of the exception (vendor.js:89306) to see which library it's coming from.

Also, your app code is using ES imports to access things that you've already handled manually via `app.import` (like the `uuid` package). That is probably going to cause double-inclusion of those packages.

**Comment by ef4** [comment] 2018-06-21 20:28
I'm closing this in favor of #26 because I can't test emberclear until we can achieve compatibility between ember-auto-import and the unreleased ember-cli version it's using.

**Closed by ef4** 2018-06-21 20:28 UTC

**Comment by NullVoxPopuli** [comment] 2018-06-21 22:14
It's possible that this error won't exist once ember-cli#master comparability is achieved. :) 
We'll see though
