### ISSUE TITLE
Getting `development` versions of modules by default

### ISSUE THREAD

**Issue by knownasilya** [ef4/ember-auto-import#555] opened 2022-12-11 20:51 UTC
Having trouble running fastboot locally because the required modules, in this case `remark-parse` imports a good many of it's dependencies as development, meaning they had `exports.development` and `exports.default` defined but for some reason node is using the development one.  I'm not doing anything weird and `NODE_ENV` isn't set anywhere.

Reproduction is here https://github.com/knownasilya/fastboot-dev-require-repro (just npm start and visit the page, error is in the console).  Running on Node v16.15.0

<details>
<summary>stacktrace</summary>
<code>
ReferenceError: document is not defined
    at eval (webpack://__ember_auto_import__/./node_modules/decode-named-character-reference/index.dom.js?:6:39)
    at Module../node_modules/decode-named-character-reference/index.dom.js (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.vendors-node_modules_ember-welcome-page_dist_components_welcome-page_js-node_modules_rehype-s-58af1e.23022ef0e16eafd5da7e.js:146:1)
    at __webpack_require__ (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.app.596ddd11b5f2e1127bd0.js:108:42)
    at eval (webpack://__ember_auto_import__/./node_modules/micromark-core-commonmark/dev/lib/character-reference.js?:6:90)
    at Module../node_modules/micromark-core-commonmark/dev/lib/character-reference.js (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.vendors-node_modules_ember-welcome-page_dist_components_welcome-page_js-node_modules_rehype-s-58af1e.23022ef0e16eafd5da7e.js:751:1)
    at __webpack_require__ (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.app.596ddd11b5f2e1127bd0.js:108:42)
    at eval (webpack://__ember_auto_import__/./node_modules/micromark/dev/lib/constructs.js?:22:84)
    at Module../node_modules/micromark/dev/lib/constructs.js (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.vendors-node_modules_ember-welcome-page_dist_components_welcome-page_js-node_modules_rehype-s-58af1e.23022ef0e16eafd5da7e.js:1180:1)
    at __webpack_require__ (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.app.596ddd11b5f2e1127bd0.js:108:42)
    at eval (webpack://__ember_auto_import__/./node_modules/micromark/dev/lib/parse.js?:11:72)
    at Module../node_modules/micromark/dev/lib/parse.js (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.vendors-node_modules_ember-welcome-page_dist_components_welcome-page_js-node_modules_rehype-s-58af1e.23022ef0e16eafd5da7e.js:1246:1)
    at __webpack_require__ (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.app.596ddd11b5f2e1127bd0.js:108:42)
    at eval (webpack://__ember_auto_import__/./node_modules/mdast-util-from-markdown/dev/lib/index.js?:7:80)
    at Module../node_modules/mdast-util-from-markdown/dev/lib/index.js (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.vendors-node_modules_ember-welcome-page_dist_components_welcome-page_js-node_modules_rehype-s-58af1e.23022ef0e16eafd5da7e.js:366:1)
    at __webpack_require__ (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.app.596ddd11b5f2e1127bd0.js:108:42)
    at eval (webpack://__ember_auto_import__/./node_modules/remark-parse/lib/index.js?:5:82)
    at Module../node_modules/remark-parse/lib/index.js (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.vendors-node_modules_ember-welcome-page_dist_components_welcome-page_js-node_modules_rehype-s-58af1e.23022ef0e16eafd5da7e.js:1510:1)
    at __webpack_require__ (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.app.596ddd11b5f2e1127bd0.js:108:42)
    at eval (webpack://__ember_auto_import__/./node_modules/remark-parse/index.js?:5:71)
    at Module../node_modules/remark-parse/index.js (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.vendors-node_modules_ember-welcome-page_dist_components_welcome-page_js-node_modules_rehype-s-58af1e.23022ef0e16eafd5da7e.js:1499:1)
    at __webpack_require__ (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/chunk.app.596ddd11b5f2e1127bd0.js:108:42)
    at Module.eval [as callback] (webpack://__ember_auto_import__/../../../../private/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/cache-332-webpack_bundler_ember_auto_import_webpack/app.cjs?:17:47)
    at Module.exports (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/vendor/loader/loader.js:104:1)
    at requireModule (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/vendor/loader/loader.js:27:1)
    at ModuleRegistry.get (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:24:1)
    at Class._extractDefaultExport (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:380:1)
    at Class.resolveOther (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:109:1)
    at Class.resolve (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:155:1)
    at resolve (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/container/index.js:788:1)
    at Registry.resolve (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/container/index.js:536:1)
    at Registry.resolve (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/container/index.js:538:1)
    at factoryFor (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/container/index.js:246:1)
    at Container.factoryFor (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/container/index.js:192:1)
    at ApplicationInstance.factoryFor (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/runtime/lib/mixins/container_proxy.js:113:1)
    at ResolverImpl.lookupHelper (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/glimmer/index.js:4470:1)
    at resolveComponentOrHelper (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/opcode-compiler.js:312:1)
    at encodeOp (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/opcode-compiler.js:2135:1)
    at pushOp (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/opcode-compiler.js:2067:1)
    at /var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/opcode-compiler.js:1781:1
    at Compilers.compile (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/opcode-compiler.js:417:1)
    at compileStatements (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/opcode-compiler.js:2070:1)
    at maybeCompile (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/opcode-compiler.js:2049:1)
    at CompilableTemplateImpl.compile (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/opcode-compiler.js:2032:1)
    at Object.evaluate (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/runtime.js:2973:1)
    at AppendOpcodes.evaluate (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/runtime.js:1052:1)
    at LowLevelVM.evaluateSyscall (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/runtime.js:4214:1)
    at LowLevelVM.evaluateInner (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/runtime.js:4185:1)
    at LowLevelVM.evaluateOuter (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/runtime.js:4178:1)
    at VM.next (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/runtime.js:5009:1)
    at VM._execute (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/runtime.js:4996:1)
    at VM.execute (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/runtime.js:4971:1)
    at /var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/runtime.js:5054:1
    at runInTrackingTransaction (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/validator.js:138:1)
    at TemplateIteratorImpl.sync (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/runtime.js:5054:1)
    at /var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/glimmer/index.js:4715:1
    at RootState.render (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/glimmer/index.js:4684:1)
    at /var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/glimmer/index.js:4980:1
    at inTransaction (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@glimmer/runtime.js:4090:1)
    at Renderer._renderRoots (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/glimmer/index.js:4962:1)
    at Renderer._renderRootsTransaction (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/glimmer/index.js:5006:1)
    at Renderer._renderRoot (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/glimmer/index.js:4951:1)
    at Renderer._appendDefinition (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/glimmer/index.js:4876:1)
    at Renderer.appendOutletView (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/@ember/-internals/glimmer/index.js:4864:1)
    at invokeWithOnError (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/backburner.js:292:1)
    at Queue.flush (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/backburner.js:197:1)
    at DeferredActionQueues.flush (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/backburner.js:360:1)
    at Backburner._end (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/backburner.js:801:1)
    at Backburner._boundAutorunEnd (/var/folders/kw/7vmtd5m91sn1kwsvblc7z1080000gn/T/broccoli-15339j12XgX6Y5NLk/out-334-broccoli_merge_trees/assets/backburner.js:525:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
</code>
</details>

---

Honestly not sure if EAI is at fault or not. I've tried everything I could think of 🤷🏼

**Comment by ef4** [comment] 2022-12-11 21:19
Please take a look and make sure you really committed what you expected to in that reproduction. It doesn't produce any errors, it doesn't have fastboot configured, and if I add fastboot it still doesn't give the error you described.

**Comment by knownasilya** [comment] 2022-12-11 21:21
@ef4 you are correct! 🤦🏼 Fixed!

**Comment by ef4** [comment] 2022-12-11 22:21
This is a duplicate of https://github.com/ef4/ember-auto-import/issues/338.

The description of this issue is misleading: "development" doesn't really matter here (and it's good that when you run `ember s` you get development versions of things, because that is development mode by default). What is breaking is `exports['.'].browser` vs `exports['.'].default` in `decode-named-character-reference/package.json`. At present you always get browser implementations.

I'm going to elaborate further in #338 on the status of this issue.

**Closed by ef4** 2022-12-11 22:21 UTC

**Comment by knownasilya** [comment] 2022-12-13 23:59
Blowing away the lock file gave me a newer version which has this

```json
  "exports": {
    ".": {
      "deno": "./index.js",
      "react-native": "./index.js",
      "worker": "./index.js",
      "browser": "./index.dom.js",
      "default": "./index.js"
    }
  },
```

EAI choses browser, so the issue persists.
