### ISSUE TITLE
Expected hash or Mixin instance, got [object Undefined] after upgrading to 2.6.0

### ISSUE THREAD

**Issue by oliverlj** [ef4/ember-auto-import#564] opened 2023-01-30 18:22 UTC
I don't know where is the problem
When I start I have this in the console with a white page

```
index.js:106 Uncaught Error: Assertion Failed: Expected hash or Mixin instance, got [object Undefined]
    at assert (index.js:106:13)
    at buildMixinsArray (mixin.js:509:13)
    at Mixin.reopen (mixin.js:435:38)
    at DebugFrameworkObject.extend (core.js:370:12)
    at Module.callback (core_view.js:13:40)
    at Module.exports (loader.js:106:1)
    at Module._reify (loader.js:143:1)
    at Module.reify (loader.js:130:1)
    at Module.exports (loader.js:104:1)
    at Module._reify (loader.js:143:1)
```

When I start the test, it says :
```
not ok 3 Chrome 109.0 - [undefined ms] - Global error: Uncaught Error: Could not find module `@ember/test-helpers` imported from `cryptofiscafacile-gui/tests/test-helper` at http://localhost:7357/assets/vendor.js, line 266
    ---
        browser log: |
            {"type":"error","text":"Uncaught Error: Could not find module `@ember/test-helpers` imported from `cryptofiscafacile-gui/tests/test-helper` at http://localhost:7357/assets/vendor.js, line 266\n","testContext":{"state":"complete"}}
           ```

**Comment by jelhan** [comment] 2023-02-11 19:51
Several users of ember-bootstrap report seeing this error after upgrading to v2.6.0. I was able to trace it down to this line of code deep in Ember's internals:

```js
define("@ember/-internals/views/lib/views/core_view", ["exports", "@ember/-internals/metal", "@ember/-internals/runtime", "@ember/object/evented", "@ember/object/-internals", "@ember/-internals/views/lib/views/states"], function (_exports, _metal, _runtime, _evented, _internals, _states) {
  "use strict";

  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  _exports.default = void 0;
  var __decorate = void 0 && (void 0).__decorate || function (decorators, target, key, desc) {
    var c = arguments.length,
      r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc,
      d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);else for (var i = decorators.length - 1; i >= 0; i--) {
      if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    }
    return c > 3 && r && Object.defineProperty(target, key, r), r;
  };
  class CoreView extends _internals.FrameworkObject.extend(_evented.default, _runtime.ActionHandler) {
    constructor() {
      super(...arguments);
      this.isView = true;
    }
   // ...
}
```

`_runtime.ActionHandler` is `undefined`. This causes the assertion to throw. It seems that `@ember/-internals/metal` resolves to an empty object.

Please find a reproduction here: https://github.com/jelhan/test-ember-bootstrap-with-ember-auto-import-v2-6-0 You will see the error when starting the application with `yarn start`.

Steps to reproduce if not using that repository:

1. Create a new Ember application with Ember CLI 4.10
2. Install Ember Bootstrap with `ember install ember-bootstrap`
3. `yarn start` and open http://localhost:4200 in Browser

The assertion is logged to the console.

**Comment by NullVoxPopuli** [comment] 2023-02-11 20:16
Do these problems exist with 2.5.0?

**Comment by ef4** [comment] 2023-02-11 20:38
@NullVoxPopuli you could use the reproduction shared above and see if the `earlyBootSet` feature you worked on addresses this case.

**Comment by jelhan** [comment] 2023-02-11 20:57
This is a regression in v2.6.0. It works fine with earlier versions as far as I know.

**Comment by NullVoxPopuli** [comment] 2023-02-11 20:59
I'll take a look at the repro

**Comment by jelhan** [comment] 2023-02-11 21:02
> I'll take a look at the repro

I created a PR showing that it works fine with v2.5.0 here: https://github.com/jelhan/test-ember-bootstrap-with-ember-auto-import-v2-6-0/pull/1

**Comment by jelhan** [comment] 2023-02-11 22:37
@NullVoxPopuli asked on Discord to test if opting out of `earlyBootSet` introduced with v2.6.0 fixes the issue. It does: https://github.com/jelhan/test-ember-bootstrap-with-ember-auto-import-v2-6-0/pull/2 This indicates even more that it is a regression introduced by v2.5.0.

Ember Bootstrap has a npm download count in the top 10% of all addons accordingly to [Ember Observer](https://emberobserver.com/addons/ember-bootstrap). The bug was reported by several people both on Discord as well as GitHub. If there isn't a quick fix, please consider rolling back the changes in v2.6.0 and releasing v2.5.0 again as v2.7.0 to mitigate the impact while debugging.

**Comment by jelhan** [comment] 2023-02-11 22:52
I thought `@ember/-internals/metal` may just be missing in the default early boot set defined. https://github.com/ef4/ember-auto-import/blob/29eab602ff01d2c89b0140a0c2c0e534ad7d5b41/packages/ember-auto-import/ts/webpack.ts#L50-L57 I tried adding it in https://github.com/jelhan/test-ember-bootstrap-with-ember-auto-import-v2-6-0/pull/3 but it doesn't seem to fix the issue.

**Comment by NullVoxPopuli** [comment] 2023-02-11 23:52
Hm, why is bootstrap importing from internal packages tho? That's not public api?

I mean, we can try adding that to the bootset, and maybe with a warning that this addon is using private api. Might be better to go that route

**Comment by NullVoxPopuli** [comment] 2023-02-12 03:09
According to the breakpoint at exception, we are trying to access this module:
```
@ember/-internals/views/lib/views/core_view
// which is imported from 
@ember/-internals/view/index
// which is imported from.... etc
@ember/internals/glimmer/index
@ember/component/index
@glimmer/component/index
__v1-addons__early-boot-set__
rsvp
@ember/-internals/runtime/lib/ext/rsvp
@ember/-internals/runtime/index
@ember/application/index
test-ember-bootstrap-with-ember-auto-import-v2.6.0/app
```
So... this error is confusing, because these modules are all available to addons and apps.

So, tabling the possibility for a module loading issue for the time being, going back the error at the top of the stack:
![image](https://user-images.githubusercontent.com/199018/218290493-33464980-5af1-431b-8767-372321db4074.png)
Silly old `CoreView`... mixing in "FrameworkObject" with "Evented" and "ActionHandler"... mixins :upside_down_face: 

but anywho, back to what the error is talking about...
one of the mixins is undefined:
![image](https://user-images.githubusercontent.com/199018/218290584-a462e015-57f1-46b7-aed1-919b988dc42b.png)
(the second one)
which is passed in here:
![image](https://user-images.githubusercontent.com/199018/218290618-bcca7077-d86e-4d66-a08b-42724b0fb9f8.png)
so... 
 - where does `_runtime.ActionHandler` come from?
 - why is it undefined?
 
 In this AMD module, it is the third param / second import: 
![image](https://user-images.githubusercontent.com/199018/218290677-9a1ae61a-0ab3-49c8-9f31-c7717867a44f.png)
which is `@ember/-internals/runtime`
![image](https://user-images.githubusercontent.com/199018/218290713-30a6d63d-8213-49a5-8480-9659edbca339.png)
And if we wanted to read nicer code, we can look here: https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/runtime/index.ts#L4

(typing in progress -- submitting comment because I don't trust form submissions when I don't save frequently)

**Comment by jelhan** [comment] 2023-02-12 09:22
> Hm, why is bootstrap importing from internal packages tho? That's not public api?

Ember Bootstrap does not import from internal packages. The error is triggered deep in the internals of Ember. It is triggered by the mixing of this class: https://github.com/emberjs/ember.js/blob/e77595745a05d160c0efec996c45adb35e569b74/packages/%40ember/-internals/views/lib/views/core_view.ts#L27

The bug is very likely not specific to Ember Bootstrap. I assume it is triggered in other cases as well. At least I'm not aware of anything very specific to Ember Bootstrap in this regard. I assume it is just noticed and reported by users of Ember Bootstrap first due to high usage of that addon.

Could we please consider switching the default for `earlyBootSet`? Enabling it by default in a minor release caused a regression affecting a relevant portion of the ecosystem. Having it disabled by default and allowing early adopters to opt-in if needed seems to be the safer option.

**Comment by NullVoxPopuli** [comment] 2023-02-12 12:47
> The error is triggered deep in the internals of Ember.

Do you read my big comment? 😅 

> Could we please consider switching the default for earlyBootSet? 

It's too late for that now, and I'd like to know why rsvp is causing all this.
The default earlyBootSet solves a ton of problems, and it's not 'just some feature', removing the defaults will break a ton of apps.

> if needed seems 

It's needed until we get core packages to the v2 format, including ember-source.

**Comment by ef4** [comment] 2023-02-12 13:23
It is not too late. It’s entirely up to us whether to roll the feature back.

I let it ship only because I didn’t have time to do what I consider the
correct solution instead (analyzing the webpack stats output to set the
correct dependencies on every AMD stub we generate), and deferred to this
one, but I still find it risky.

**Comment by jelhan** [comment] 2023-02-12 13:57
> removing the defaults will break a ton of apps

Do you have data backing that one? I haven't seen much bug reports for v2.5.0 and earlier versions related to this. It would be surprising if many apps started to rely on this default behavior in the last few weeks.

**Comment by NullVoxPopuli** [comment] 2023-02-12 14:13
Have you read through #504 ? 
the issue is really hard to grok, and anyone running in to it will hold off on adopting v2 addons.
When that particular issue comes up, folks may not even know what the issue is, because of how errors are reported.

For example, the class of issues resolved by the fix to #504 is most commonly presented as:
 - `decorator is not a function`
    this issue is when a v2 addon imports something from a v1 addon and that v1 addon immediately invokes something in module space. Not something we can can get away from for as long as we use legacy decorators.
 
 >  I haven't seen much bug reports for v2.5.0
 
Issue #504 affected all ember-auto-import versions supporting v2 addons prior to 2.6.0.
It has been a major blocker for mass adoption of v2 addons. 
I'm 100% certain I'm not the only one (I didn't report the original issue), but in a company that maintains >= 180 ember projects, we run in to stuff, and due to the scale, that stuff becomes blockers. 
Some people would give up, potentially thinking to themselves "oh, there is nothing I can do", "this is broken", "this looks like this other similarly reported error (maybe: https://github.com/ef4/ember-auto-import/issues/536)", and then not proceed with incremental v2 addon conversion across the ecosystem.
Converting addons to the v2 format is essential for our long term success and performance :tada: 

----------------

While I agree we need to fix the issue affecting RSVP / ember-bootstrap, I do not agree with _removing the feature_, especially considering the temporary work-around.

Could I personally deal with churn in this feature if we were to roll it back / make it opt in? absolutely.
But I do not have any confidence that doing so would make things better for the whole of users, especially as more of the ecosystem converts to v2 addons. (I kinda think it would make things worse, as people are more likely to run in to #504 than when the problem was "fixed" :upside_down_face: )

**Comment by ef4** [comment] 2023-02-12 14:59
@NullVoxPopuli until someone produces a complete description of what's causing *this* issue, you have no way of knowing whether it's rare or common, or whether #533 *actually* fixed #504, or just fixed some cases and made others worse.

If you can't figure it out, and if I don't have time to do it for you soon, rolling back is the better thing for the community because an old bug that people were living with is better than destabilizing previously stable patterns with a new bug of unknown severity.

**Comment by NullVoxPopuli** [comment] 2023-02-12 15:02
I will be digging deeper tomorrow

**Comment by NullVoxPopuli** [comment] 2023-02-12 17:24
Except, this whole thing bothers me and I don't feel like I can relax :( 

further investigation / things I've noticed:
 - empty early bootset = no error
 - testing individual entries from the default earlyBootSet.
    - only `@glimmer/component` error
    - only `@glimmer/tracking` - no error
    - only `@ember/service` - error
    - only `@ember/controller` - error
    - only `@ember/component` - error
    - only `@ember/routing/route` - error

Not really super helpful, because these are all things from within ember-source (aside from `@glimmer/component`)

But, searching for what the early-boot-set is applied to when `@ember/routing/route` is only added gives us a snapshot in to what the early boot set is applied to (without too much noise):
![image](https://user-images.githubusercontent.com/199018/218326570-b8036b43-5923-4b84-9161-303addef81d4.png)


so, this is probably why things are going haywire -- RSVP has a dependency on the early boot set, which includes v1 addons (ember-source during the error case), but ember-source depends on RSVP -- so **we have a cycle**

**Comment by NullVoxPopuli** [comment] 2023-02-12 17:46
<details><summary>

yeah, [this is "a" fix](https://github.com/NullVoxPopuli/test-ember-bootstrap-with-ember-auto-import-v2-6-0/blob/main/patches/ember-auto-import%2B2.6.0.patch)

</summary>

```diff
diff --git a/node_modules/ember-auto-import/js/webpack.js b/node_modules/ember-auto-import/js/webpack.js
index 99bbc10..a0311f8 100644
--- a/node_modules/ember-auto-import/js/webpack.js
+++ b/node_modules/ember-auto-import/js/webpack.js
@@ -78,6 +78,10 @@ handlebars_1.registerHelper('js-string-escape', js_string_escape_1.default);
 handlebars_1.registerHelper('join', function (list, connector) {
     return list.join(connector);
 });
+handlebars_1.registerHelper('is-in-ember-source', function (modulePath) {
+  // TODO: how to determine if ember-source has stopped bundling these?
+  return ['rsvp', '@glimmer/component', '@glimmer/tracking'].some(dep => modulePath.startsWith(dep));
+});
 const entryTemplate = handlebars_1.compile(`
 module.exports = (function(){
   var d = _eai_d;
@@ -95,7 +99,11 @@ module.exports = (function(){
   };
   d('__v1-addons__early-boot-set__', [{{{v1EmberDeps}}}], function() {});
   {{#each staticImports as |module|}}
-    d('{{js-string-escape module.specifier}}', ['__v1-addons__early-boot-set__'], function() { return require('{{js-string-escape module.specifier}}'); });
+    d('{{js-string-escape module.specifier}}', [
+      {{#unless (is-in-ember-source module.specifier)}}
+        '__v1-addons__early-boot-set__'
+      {{/unless}}
+    ], function() { return require('{{js-string-escape module.specifier}}'); });
   {{/each}}
   {{#each dynamicImports as |module|}}
     d('_eai_dyn_{{js-string-escape module.specifier}}', [], function() { return import('{{js-string-escape module.specifier}}'); });

```

</details>
 
now that I have a path to explore and add an automated test for (thanks for the reproduction @jelhan !!), I can relax, and finish this tomorrow (for reals this time)

**Comment by jelhan** [comment] 2023-02-18 13:29
@NullVoxPopuli @ef4 Any update on this one? We got this reported by additional users of Ember Bootstrap in this week. In case the bug fix needs a few more days or weeks, please consider rolling back or at least changing default value as interim solution.

**Comment by NullVoxPopuli** [comment] 2023-02-18 14:38
I submitted a PR here: https://github.com/ef4/ember-auto-import/pull/566

**Comment by Esaron** [comment] 2023-02-18 16:27
I believe this issue caused two site-wide outages for my company in the past month and stumped most of us for a not-insignificant amount of time. First was an Ember upgrade that included the `ember-auto-import` dependency bump, then the dependency bump on its own (which we were holding off on due to the Ember upgrade being in flight). We independently narrowed down the issue to RSVP and pulled it out of a fork of `ember-bootstrap` to get things working, but an upstream fix would be preferable.

**Comment by ef4** [comment] 2023-02-22 16:15
Fixed by #568 in release 2.6.1.

**Closed by ef4** 2023-02-22 16:15 UTC

**Comment by jelhan** [comment] 2023-02-24 08:26
Can confirm that it is fixed. Haven't tested myself. But serveral users of Ember Bootstrap reports that it's working again. Thanks a lot.

**Comment by simonihmig** [comment] 2023-02-28 20:11
I just spent a few hours on the opposite case. Nevertheless posting here, as a lot of the discussion around #504 was taking place here...

I have a reproduction at https://github.com/CrowdStrike/ember-headless-form/tree/eai-repro (run `pnpm start` and see `/tests`), where:
* a v2 addon (ember-headless-form) depends on another v2 addon (ember-async-data)
* ember-async-data's use of `@tracked` fails with `decorator is not a function`
* the app itself seems to work, but a lot of tests are failing with that above mentioned exception. They are .gts based, so import the component from ember-headless-form explicitly. And some are importing `@tracked` also...
* at the time the error happens, `__webpack_require__('@glimmer/tracking')` returns an empty object. When calling that later (like manually in the console), it correctly returns the `tracked` export. 
* also, this code was correctly working, until I rebased my branch. Somehow it seems this changed timing/order of module resolution, which surfaced the problem
* I don't see a v1 addon taking a significant role in the party here 

Given that, it is possible to fix this using either:
* eai v2.6.0 (i.e. including @NullVoxPopuli's #553) 
* eai v2.6.1 and `earlyBootSet: () => ['@glimmer/tracking']`

So it seems again we don't have a version that "just works"(TM)
