### ISSUE TITLE
Incompatibility with JS preprocessors for non-JS code

### ISSUE THREAD

**Issue by omarestrella** [ef4/ember-auto-import#46] opened 2018-06-29 13:25 UTC
First of all, thanks for the work!

Primary issue: Using `ember-elm` + `ember-auto-import` causes `ember-elm` to not see Elm modules in the app tree, resulting in elm code not being included in the resulting app build.
Example repo: https://github.com/omarestrella/elm-test

When attempting to move some `app.import`'d and `broccoli-funnel`'d libraries over to using auto-import, I noticed that this addon caused ember-elms preprocessor to not work since any non-JS code is not included in the resulting app tree. By the time the tree hits the addons Elm compiler, no Elm files are found.

Is there a way around this at the moment?

Some example output I am expecting to see in the final app build:

```javascript
if (typeof exports == 'undefined') {
  define('elm-test/elm-modules', ['exports'], function (exports) {
    exports['default'] = Elm;
  });
} else {
  exports['default'] = Elm;
}
```

That is missing once you include ember-auto-import addon and build the project.

**Comment by lsg-richard** [comment] 2018-07-06 04:43
I've just noticed that adding `ember-auto-import` to a project stops `ember-cli-anything-to-js` from working - is this the same underlying issue?

I use the latter to easily bring in WebGL vertex and fragment shader files as strings that can be imported using ES6 syntax.

**Comment by lsg-richard** [comment] 2018-07-09 08:13
Is `ember-auto-import` trying to act as a catch-all and resolve everything to NPM? If so, and it's inserted with too high of a precedence, then it would make sense that these other Ember CLI addons which add their own nodes to the tree start failing all of a sudden.

**Comment by lsg-richard** [comment] 2018-07-09 21:35
Unfortunately this still isn't working in v1.1.0, though `ember-auto-import` does now include the relevant content in the build which is a definite step in the right direction.

The problem is that the included source appears to not be transpiled. So I'm getting transpiled source that still includes ES6 style `export default ...` just sitting in the large application JS bundle, and then an `Unexpected token export` error appears on page load. This is happening when using the `ember-cli-anything-to-js` addon, which I admit is a bit out of date, but does work fine with `ember-browserify` which is what we're upgrading from.

I'll have a look at the PR that was merged and see if I can figure out what's going on.

**Comment by ef4** [comment] 2018-07-09 22:58
I think the remaining bug is in ember-cli-anything-to-js. It needs to
declare itself as going before ember-cli-babel. See how ember-auto-import
does the same thing in package.json.

Without that declaration, it comes down to luck, and will work in some apps
and not others, depending on the total set of addons and their inclusion
order.

**Comment by lsg-richard** [comment] 2018-07-10 10:41
Thanks so much for that, I've got it all working now and have submitted a PR to that project for the fix you outlined.

**Closed** 2018-07-10 18:18 UTC
