### ISSUE TITLE
ember-auto-import breaks assets rewriting

### ISSUE THREAD

**Issue by lucacorti** [ef4/ember-auto-import#94] opened 2018-08-08 10:03 UTC
Hi,

When fingerprint prepend is set and `ember-auto-import` >= 1.2.7 is installed, the asset rewriter receives an invalid path and breaks the build:

```Error: Build Canceled: Broccoli Builder ran into an error with `AssetRewrite` plugin. 💥
Cannot read property '2' of null
TypeError: Cannot read property '2' of null
    at AssetRewrite.rewriteAssetPath (node_modules/broccoli-asset-rewrite/index.js:127:91)
    at AssetRewrite.processString (node_modules/broccoli-asset-rewrite/index.js:167:24)
    at AssetRewrite.processFile (node_modules/broccoli-filter/index.js:165:31)
    at asyncProcessFile (node_modules/broccoli-filter/index.js:122:21)
    at tryCatch (node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (node_modules/rsvp/dist/rsvp.js:538:13)
    at node_modules/rsvp/dist/rsvp.js:606:14
    at flush (node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)Pipeline aborted```

Pinning `ember-auto-import` to `1.2.6` solves the problem.

**Comment by ef4** [comment] 2018-08-08 18:25
I can't reproduce. What packages are you trying to auto import?

Also, can you put a breakpoint or console.log at the site of the exception and tell me the values of `replaceString` and `this.prepend`?

**Comment by lucacorti** [comment] 2018-08-08 18:54
I'm not pulling in auto import directly, it is pulled in by `ember-intl` which is my dependency. I did some debug but don't have it at hand right know. I'll provide it asap but IIRC at some point replaceString contained something along the lines of `var ember_auto_import`.

**Comment by ef4** [comment] 2018-08-09 14:54
Thanks, that helped me find this: https://github.com/rickharrison/broccoli-asset-rewrite/issues/65

That is the underlying cause.

**Comment by ef4** [comment] 2018-08-09 15:02
When https://github.com/rickharrison/broccoli-asset-rewrite/pull/64 is merged and released it will fix this issue.

You can probably workaround by disabling sourcemaps:

```js
let app = new EmberApp(defaults, {
    sourcemaps: { enabled: false}
});
```

**Closed by ef4** 2018-08-09 15:02 UTC

**Comment by sumeetattree** [comment] 2019-03-03 16:19
I just ran into this issue with `fingerprinting.enabled = true`. Setting this to false makes the build succeed. This fails with `"broccoli-asset-rewrite": "^1.1.0"` but is fine on the `"broccoli-asset-rewrite": "^2.0.0"`. But `ember-cli: 3.8` does not ship with the latest version of `asset-rewrite`
